Updated Jenkins Pipeline

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,43 +1,45 @@
+```groovy
 pipeline {
 
     agent any
 
     environment {
         IMAGE_NAME = "arbaz186/company-devops-project"
-        IMAGE_TAG = "${BUILD_NUMBER}"
+        CONTAINER_NAME = "company-website"
+        PORT = "8085"
     }
 
     stages {
 
-        stage('Project Information') {
+        stage('Git Checkout') {
             steps {
-                echo 'Starting Company DevOps CI/CD Pipeline'
-            }
-        }
-
-        stage('Check Docker') {
-            steps {
-                sh 'docker --version'
+                checkout scm
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} app'
+                sh '''
+                docker build -t ${IMAGE_NAME}:latest app
+                '''
             }
         }
 
-        stage('Push Docker Image') {
-            steps {
-                sh 'docker push ${IMAGE_NAME}:${IMAGE_TAG}'
-            }
-        }
-
-        stage('Update Kubernetes') {
+        stage('Stop Old Container') {
             steps {
                 sh '''
-                sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" kubernetes/deployment.yaml
-                kubectl apply -f kubernetes/deployment.yaml
+                docker rm -f ${CONTAINER_NAME} || true
+                '''
+            }
+        }
+
+        stage('Run New Container') {
+            steps {
+                sh '''
+                docker run -d \
+                --name ${CONTAINER_NAME} \
+                -p ${PORT}:80 \
+                ${IMAGE_NAME}:latest
                 '''
             }
         }
@@ -45,13 +47,21 @@ pipeline {
     }
 
     post {
+
         success {
-            echo 'Deployment Successful'
+            echo "=================================="
+            echo "Deployment Successful"
+            echo "Website Updated Successfully"
+            echo "=================================="
         }
 
         failure {
-            echo 'Deployment Failed'
+            echo "=================================="
+            echo "Deployment Failed"
+            echo "=================================="
         }
+
     }
 
 }
+```
